/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.fire_alarm_system;
import com.mycompany.fire_alarm_system.Configure;
import com.mycompany.fire_alarm_system.Register;
/**
 *
 * @author HP
 */

import static com.mycompany.fire_alarm_system.Mainsc.dashboard;
import static com.mycompany.fire_alarm_system.Mainsc.f0;
import static com.mycompany.fire_alarm_system.Mainsc.f1;
import static com.mycompany.fire_alarm_system.Mainsc.f2;
import static com.mycompany.fire_alarm_system.Mainsc.f3;
import static com.mycompany.fire_alarm_system.Mainsc.f4;
import static com.mycompany.fire_alarm_system.Mainsc.f5;
import java.util.Map.Entry;
import javax.swing.*;

public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register_a_sensor
     */
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 0));

        jLabel1.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sensor ID:");

        jLabel2.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Sensor Type:");

        jLabel3.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Floor No:");

        jLabel4.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Install Location:");

        jTextField1.setBackground(new java.awt.Color(108, 120, 137));
        jTextField1.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 16)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(228, 241, 254));
        jTextField1.setOpaque(false);

        jComboBox1.setBackground(new java.awt.Color(108, 120, 137));
        jComboBox1.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 16)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CO Sensor", "Heat Sensor", "Smoke Sensor", " " }));
        jComboBox1.setToolTipText("Choose sensor type");
        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBox1.setName(""); // NOI18N
        jComboBox1.setOpaque(false);

        jTextField2.setBackground(new java.awt.Color(108, 120, 137));
        jTextField2.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 16)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(228, 241, 254));
        jTextField2.setOpaque(false);

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("BACK");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(51, 51, 0));

        jLabel6.setBackground(new java.awt.Color(204, 204, 204));
        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 46)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("REGISTER");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(406, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap(383, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("SAVE");
        jButton3.setToolTipText("");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jComboBox2.setBackground(new java.awt.Color(108, 120, 137));
        jComboBox2.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 16)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Room 1", "Room 2", "Room 3", "Room 4", "Room 5", "Room 6", "Lab 1", "Lab 2", "Stairs 1", "Stairs 2", "Hall", " " }));
        jComboBox2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBox2.setOpaque(false);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("CONFIGURE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addComponent(jTextField1)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jComboBox1.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //ActionListener for canceling the registration and directing to MainScreen window.
    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        Mainsc.dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2MouseClicked
    //ActionListener for saving data of registered sensor and directing to MainScreen window.
    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        int fl = 0;

        if ("".equals(jTextField1.getText())) {
            fl += 4;
        }
        if ((!jTextField2.getText().matches("[0-5]$"))) {
            fl = fl + 2;
        }
        for (Entry<String, Location> mp : f0.entrySet()) {
            if (mp.getValue().Cid.equals(jTextField1.getText()) || mp.getValue().Hid.equals(jTextField1.getText()) || mp.getValue().Sid.equals(jTextField1.getText())) {
                fl++;
            }
        }
        for (Entry<String, Location> mp : f1.entrySet()) {
            if (mp.getValue().Cid.equals(jTextField1.getText()) || mp.getValue().Hid.equals(jTextField1.getText()) || mp.getValue().Sid.equals(jTextField1.getText())) {
                fl++;
            }
        }
        for (Entry<String, Location> mp : f2.entrySet()) {
            if (mp.getValue().Cid.equals(jTextField1.getText()) || mp.getValue().Hid.equals(jTextField1.getText()) || mp.getValue().Sid.equals(jTextField1.getText())) {
                fl++;
            }
        }
        for (Entry<String, Location> mp : f3.entrySet()) {
            if (mp.getValue().Cid.equals(jTextField1.getText()) || mp.getValue().Hid.equals(jTextField1.getText()) || mp.getValue().Sid.equals(jTextField1.getText())) {
                fl++;
            }
        }
        for (Entry<String, Location> mp : f4.entrySet()) {
            if (mp.getValue().Cid.equals(jTextField1.getText()) || mp.getValue().Hid.equals(jTextField1.getText()) || mp.getValue().Sid.equals(jTextField1.getText())) {
                fl++;
            }
        }
        for (Entry<String, Location> mp : f5.entrySet()) {
            if (mp.getValue().Cid.equals(jTextField1.getText()) || mp.getValue().Hid.equals(jTextField1.getText()) || mp.getValue().Sid.equals(jTextField1.getText())) {
                fl++;
            }
        }

        switch (fl) {
            case 0: {
                Sensors s1 = new Sensors();

                s1.SensorID = jTextField1.getText();
                s1.floorno = Integer.parseInt(jTextField2.getText());
                s1.location = jComboBox2.getSelectedItem().toString();
                s1.SensorType = jComboBox1.getSelectedItem().toString();

                Location L = new Location();
                switch (s1.SensorType) {
                    case "Smoke Sensor":
                        L.Sid = s1.SensorID;
                        break;
                    case "Heat Sensor":
                        L.Hid = s1.SensorID;
                        break;
                    case "CO Sensor":
                        L.Cid = s1.SensorID;
                        break;
                }

                switch (s1.floorno) {
                    case 0:
                        if (f0.containsKey(s1.location)) {
                            switch (s1.SensorType) {
                                case "Smoke Sensor":
                                    f0.get(s1.location).Sid = s1.SensorID;
                                    break;
                                case "Heat Sensor":
                                    f0.get(s1.location).Hid = s1.SensorID;
                                    break;
                                case "CO Sensor":
                                    f0.get(s1.location).Cid = s1.SensorID;
                                    break;
                            }
                        } else {
                            f0.put(s1.location, L);
                        }
                        break;
                    case 1:
                        if (f1.containsKey(s1.location)) {
                            switch (s1.SensorType) {
                                case "Smoke Sensor":
                                    f1.get(s1.location).Sid = s1.SensorID;
                                    break;
                                case "Heat Sensor":
                                    f1.get(s1.location).Hid = s1.SensorID;
                                    break;
                                case "CO Sensor":
                                    f1.get(s1.location).Cid = s1.SensorID;
                                    break;
                            }
                        } else {
                            f1.put(s1.location, L);
                        }
                        break;
                    case 2:
                        if (f2.containsKey(s1.location)) {
                            switch (s1.SensorType) {
                                case "Smoke Sensor":
                                    f2.get(s1.location).Sid = s1.SensorID;
                                    break;
                                case "Heat Sensor":
                                    f2.get(s1.location).Hid = s1.SensorID;
                                    break;
                                case "CO Sensor":
                                    f2.get(s1.location).Cid = s1.SensorID;
                                    break;
                            }
                        } else {
                            f2.put(s1.location, L);
                        }
                        break;
                    case 3:
                        if (f3.containsKey(s1.location)) {
                            switch (s1.SensorType) {
                                case "Smoke Sensor":
                                    f3.get(s1.location).Sid = s1.SensorID;
                                    break;
                                case "Heat Sensor":
                                    f3.get(s1.location).Hid = s1.SensorID;
                                    break;
                                case "CO Sensor":
                                    f3.get(s1.location).Cid = s1.SensorID;
                                    break;
                            }
                        } else {
                            f3.put(s1.location, L);
                        }
                        break;
                    case 4:
                        if (f4.containsKey(s1.location)) {
                            switch (s1.SensorType) {
                                case "Smoke Sensor":
                                    f4.get(s1.location).Sid = s1.SensorID;
                                    break;
                                case "Heat Sensor":
                                    f4.get(s1.location).Hid = s1.SensorID;
                                    break;
                                case "CO Sensor":
                                    f4.get(s1.location).Cid = s1.SensorID;
                                    break;
                            }
                        } else {
                            f4.put(s1.location, L);
                        }
                        break;
                    case 5:
                        if (f5.containsKey(s1.location)) {
                            switch (s1.SensorType) {
                                case "Smoke Sensor":
                                    f5.get(s1.location).Sid = s1.SensorID;
                                    break;
                                case "Heat Sensor":
                                    f5.get(s1.location).Hid = s1.SensorID;
                                    break;
                                case "CO Sensor":
                                    f5.get(s1.location).Cid = s1.SensorID;
                                    break;
                            }
                        } else {
                            f5.put(s1.location, L);
                        }
                        break;
                }

                JOptionPane.showMessageDialog(this, "Sensor Registered.");
                Register R = new Register();
                R.setVisible(true);
                this.dispose();
                break;
            }
            case 1:
                JOptionPane.showMessageDialog(this, "This ID is already registered");
                Register R2 = new Register();
                R2.setVisible(true);
                this.dispose();
                break;
            case 2:
                JOptionPane.showMessageDialog(this, "Entered floor doesn't exist in CC3!");
                Register R3 = new Register();
                R3.setVisible(true);
                this.dispose();
                break;
            case 3:
                JOptionPane.showMessageDialog(this, "Entered Sensor ID is already registered and entered floor doesn't exist in CC3!");
                Register R4 = new Register();
                R4.setVisible(true);
                this.dispose();
                break;
            case 4:
                JOptionPane.showMessageDialog(this, "invalid Sensor ID");
                Register R5 = new Register();
                R5.setVisible(true);
                this.dispose();
                break;
            case 6:
                JOptionPane.showMessageDialog(this, "Please fill valid sensor ID and entered floor doesn't exist in CC3!");
                Register R6 = new Register();
                R6.setVisible(true);
                this.dispose();
                break;
        }
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Configure configsc = new Configure();
        configsc.setVisible(true);
        Register regisc = new Register();
        regisc.setVisible(false);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
